#ifndef DEFINATION_H_INCLUDED
#define DEFINATION_H_INCLUDED

enum BulletAttackType
{
    BULLET_ATTACK_PLAYER,
    BULLET_ATTACK_ENEMY,
    BULLET_ATTACK_NULL = 0x7FFFFFFF
};

enum BulletType
{
    BULLET_CIRCLE_RED,
    BULLET_CIRCLE_ORANGE,
    BULLET_CIRCLE_YELLOW,
    BULLET_CIRCLE_GREEN,
    BULLET_CIRCLE_CYAN,
    BULLET_CIRCLE_BLUE,
    BULLET_CIRCLE_PURPLE,
    BULLET_CIRCLE_BLACK,
    BULLET_CIRCLE_WHITE,
    BULLET_TYPE_NULL = 0x7FFFFFFF
};

enum SceneName
{
    SCENE_MAIN_MENU,
    SCENE_GAME_LOOP,
    SCENE_NULL = 0x7FFFFFFF
};

enum GameLayer
{
    GAME_LAYER_BACK_0,
    GAME_LAYER_BACK_1,
    GAME_LAYER_ALIVE,
    GAME_LAYER_BULLET_0,
    GAME_LAYER_BULLET_1,
    GAME_LAYER_JUDGE,
    GAME_LAYER_EVENT_0,
    GAME_LAYER_EVENT_1,
    GAME_LAYER_NUM,
    GAME_LAYER_NULL = 0x7FFFFFFF
};

#endif
